apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    
    scrape_configs:
      - job_name: 'taskmanager-backend'
        static_configs:
          - targets: ['backend:5000']
        metrics_path: '/metrics'
        scrape_interval: 30s
        
      - job_name: 'victoria-metrics'
        static_configs:
          - targets: ['victoria-metrics:8428']
        metrics_path: '/metrics'
        scrape_interval: 30s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmagent
  labels:
    app: vmagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmagent
  template:
    metadata:
      labels:
        app: vmagent
    spec:
      containers:
      - name: vmagent
        image: victoriametrics/vmagent:latest
        args:
        - -promscrape.config=/etc/prometheus/prometheus.yml
        - -remoteWrite.url=http://victoria-metrics:8428/api/v1/write
        ports:
        - containerPort: 8429
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: config
        configMap:
          name: vmagent-config
---
apiVersion: v1
kind: Service
metadata:
  name: vmagent
  labels:
    app: vmagent
spec:
  selector:
    app: vmagent
  ports:
  - name: http
    port: 8429
    targetPort: 8429
  type: ClusterIP